proc1: 
  cmd: nginx -c /etc/nginx/nginx.conf
  numprocs: 1
  stopsignal: TERM
  stoptime: 5
  # stdout: /tmp/nginx.stdout
  # stderr: /tmp/nginx.stderr
proc2:
  cmd: /bin/sh -c python prograwefms/process2.py
  stoptime: 2
  stopsignal: TERM
  numprocs: 1
  # stderr: proc.stderr
  # stdout: proc.stdout
ls_proc:
  cmd: /bin/ls
ls_no_bin:
  cmd: ls