proc1: 
  cmd: nginx -c /etc/nginx/nginx.conf
  numprocs: 1
  stopsignal: TERM
  stoptime: 5
  # stdout: /tmp/nginx.stdout
  # stderr: /tmp/nginx.stderr
  onstart: false
proc2:
  cmd: python programs/process2.py
  stoptime: 2
  stopsignal: TERM
  numprocs: 2
  # stderr: proc.stderr
  # stdout: proc.stdout
  onstart: true
quitter:
  cmd: python programs/quitter.py
  onstart: true
  restart: onerror
  expected:
    - 0
ls_proc:
  cmd: /bin/ls
ls_no_bin:
  cmd: ls